name: Java CI with Gradle
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build with Gradle
        run: chmod +x ./gradlew
      - name: Build Action
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: shadowJar
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SkHttp
          path: build/libs/**

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: build/libs
      - name: Run tests
        uses: SkriptLang/skript-test-action@v1.1
        with:
          test_script_directory: src/test/scripts
          extra_plugins_directory: build/libs