name: Java CI with Gradle
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build with Gradle
        run: chmod +x ./gradlew
      - name: Build Action
        uses: gradle/gradle-build-action@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
        with:
          arguments: shadowJar
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SkHttp
          path: build/libs/**
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run tests
        uses: SkriptLang/skript-test-action@v1.1
        with:
          test_script_directory: src/test/scripts
          skript_repo_ref: 2.8.5
          extra_plugins_directory: extra-plugins/